application: cloudinologger
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

#- url: /admin/.*
#  script: $PYTHON_LIB/google/appengine/ext/admin
#  login: admin

- url: .*
  script: server/main.py
#  login: admin

libraries:
- name: django
  version: "1.2"

builtins:
- remote_api: on
- appstats: on
